// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTT09bHvnYrPk_Gm6hAa3CgU3IlgVyEvM',
    appId: '1:87233152428:web:92cc635d0291a403ede609',
    messagingSenderId: '87233152428',
    projectId: 'handleliste-f1659',
    authDomain: 'handleliste-f1659.firebaseapp.com',
    storageBucket: 'handleliste-f1659.firebasestorage.app',
    measurementId: 'G-EV424HE9XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPTvHdnz_hBbfDMnZ9JRiO9hnm2jnobMk',
    appId: '1:87233152428:android:267dfc5548277115ede609',
    messagingSenderId: '87233152428',
    projectId: 'handleliste-f1659',
    storageBucket: 'handleliste-f1659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTy_omSd8wwA4K9KBZKsrwdOTM7rdvzLs',
    appId: '1:87233152428:ios:fe9b10fd5133098dede609',
    messagingSenderId: '87233152428',
    projectId: 'handleliste-f1659',
    storageBucket: 'handleliste-f1659.firebasestorage.app',
    androidClientId: '87233152428-dm3ej4qv3nmmi7kmhhhg63apbbj160h6.apps.googleusercontent.com',
    iosClientId: '87233152428-r3gmu5tep1fddotpml0hvrin5pvk4ojp.apps.googleusercontent.com',
    iosBundleId: 'no.ktkappfabrikk.handlelisteApp',
  );
}
